set(CADINSPECT_VERSION "0.1.0")
set(CADINSPECT_FILE_VERSION "0.1.0.0")
set(CADINSPECT_VERSION_MAJOR 0)
set(CADINSPECT_VERSION_MINOR 1)
set(CADINSPECT_VERSION_PATCH 0)
set(CADINSPECT_VERSION_BUILD 0)

set(CADINSPECT_PRODUCT_NAME "CADInspect")
set(CADINSPECT_COMPANY_NAME "CADInspect Project")
set(CADINSPECT_LEGAL_COPYRIGHT
    "Copyright (c) 2026 CADInspect contributors")
